spring:
  dataSource:
    url: jdbc:mysql://39.107.100.75:3306/bysj?useUnicode=yes&amp
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

    max-idle: 10
    max-wait: 10000
    .min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)


  freemarker:
    suffix: .ftl
    # 配置 freemarker的内容编码
    charset: UTF-8
    # 配置视图的输出HTML的content type
    content-type: text/html;charset=UTF-8
    # 配置freemarker的文件编码
    default_encoding: UTF-8
    # 是否在mode自动把session中的attribute导出来
    expose-session-attributes: true
    # 配置静态文件路径
    static-locations=classpath: /META-INF/resources/,classpath:/resources/static/,classpath:/static/,classpath:/public

